
import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author erik.sandlov
 */
public class grafik extends javax.swing.JPanel {
int length=0;
    /**
     * Creates new form grafik
     */
    public grafik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        slide = new javax.swing.JSlider();
        startButton = new javax.swing.JButton();

        text.setText("Antal kvadrater");

        slide.setMajorTickSpacing(1);
        slide.setMaximum(12);
        slide.setMinorTickSpacing(1);
        slide.setSnapToTicks(true);
        slide.setValue(5);

        startButton.setText("Go");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(startButton))
                    .addComponent(text))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startButton))
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        length=slide.getValue();
        repaint();
    }//GEN-LAST:event_startButtonActionPerformed
@Override
protected void paintComponent(Graphics g){
    super.paintComponent(g);
    if(length<=6){
    for (int i = 0; i < length; i++) {
        g.fillRect(20+(i*60), 20, 40, 40);
    }}
    else{
        for (int i = 0; i < 6; i++) {
        g.fillRect(20+(i*60), 20, 40, 40);
    }
        for (int i = 0; i < length-6; i++) {
        g.fillRect(20+(i*60), 80, 40, 40);
        
    }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider slide;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
