/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author erik.sandlov
 */
public class panel extends javax.swing.JPanel {

    static Person[] personer = new Person[200];
    static int pCount = 0;

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        addPerson = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        comboBox = new javax.swing.JComboBox<>();

        jLabel1.setText("Namn");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Ålder");

        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });

        addPerson.setText("Lägg till");
        addPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        comboBox.setMaximumRowCount(4);
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-Ö", "Ö-A", "Ålder fall", "Ålder stig" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addPerson)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(addPerson)))
                .addGap(53, 53, 53)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
        textArea.setText("");

        int sorttype = this.comboBox.getSelectedIndex();
        sort(sorttype);
        textArea.setText("");
        for (int i = 0; i < pCount; i++) {
            textArea.append(personer[i].toString() + "\n");
        }
    }//GEN-LAST:event_comboBoxActionPerformed

    private void addPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonActionPerformed
        // TODO add your handling code here:
        personer[pCount] = new Person(this.nameField.getText(), Integer.valueOf(this.ageField.getText()));
        textArea.append(personer[pCount].toString() + "\n");
        pCount++;
        this.nameField.setText("");
        this.ageField.setText("");
        textArea.setText("");

        int sorttype = this.comboBox.getSelectedIndex();
        sort(sorttype);
        textArea.setText("");
        for (int i = 0; i < pCount; i++) {
            textArea.append(personer[i].toString() + "\n");
        }
        
    }//GEN-LAST:event_addPersonActionPerformed
    
    public static void selectionSortNameA(Person[] lista) {

        for (int i = 0; i < pCount - 1; i++) {
            int index = i;
            for (int j = i; j < pCount; j++) {
                if (lista[j].getName().compareToIgnoreCase(lista[index].getName()) < 0) {
                    index = j;
                }
            }
            Person temp = lista[index];
            lista[index] = lista[i];
            lista[i] = temp;

        }
    }
    public static void sort(int sorttype){
        switch (sorttype) {
            case 0:
                selectionSortNameA(personer);
                break;
            case 1:
                selectionSortNameÖ(personer);
                break;
            case 2:
                selectionSortAge0(personer);
                break;
            case 3:
                selectionSortAge99(personer);
                break;
        }
        
    }
    public static void selectionSortNameÖ(Person[] lista) {

        for (int i = 0; i < pCount - 1; i++) {
            int index = i;
            for (int j = i; j < pCount; j++) {
                if (lista[j].getName().compareToIgnoreCase(lista[index].getName()) > 0) {
                    index = j;
                }
            }
            Person temp = lista[index];
            lista[index] = lista[i];
            lista[i] = temp;

        }
    }

    public static void selectionSortAge0(Person[] lista) {

        for (int i = 0; i < pCount - 1; i++) {
            int index = i;
            for (int j = i; j < pCount; j++) {
                if (lista[j].getAge() > lista[index].getAge()) {
                    index = j;
                }
            }
            Person temp = lista[index];
            lista[index] = lista[i];
            lista[i] = temp;

        }
    }

    public static void selectionSortAge99(Person[] lista) {

        for (int i = 0; i < pCount - 1; i++) {
            int index = i;
            for (int j = i; j < pCount; j++) {
                if (lista[j].getAge() < lista[index].getAge()) {
                    index = j;
                }
            }
            Person temp = lista[index];
            lista[index] = lista[i];
            lista[i] = temp;

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPerson;
    private javax.swing.JTextField ageField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
