
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ERIK
 */
public class CalcPanel extends javax.swing.JPanel {

    /**
     * Creates new form CalcPanel
     */
    public CalcPanel() {
        initComponents();
        this.jtf0.setVisible(false);
        this.jtf1.setVisible(false);
        this.jl0.setVisible(false);
        this.jl1.setVisible(false);
        this.jButtonOk.setVisible(false);
        this.jtaCList.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConstruciton = new javax.swing.JLabel();
        jcbConstruction = new javax.swing.JComboBox<>();
        jtf0 = new javax.swing.JTextField();
        jtf1 = new javax.swing.JTextField();
        jl0 = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jl1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCList = new javax.swing.JTextArea();

        jLabelConstruciton.setText("Konstruktion");

        jcbConstruction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj", "Trappa", "Husgrund" }));
        jcbConstruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbConstructionActionPerformed(evt);
            }
        });

        jl0.setText("test");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jl1.setText("test");

        jtaCList.setColumns(20);
        jtaCList.setRows(5);
        jScrollPane1.setViewportView(jtaCList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabelConstruciton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbConstruction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf0, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl0)
                        .addGap(21, 21, 21)
                        .addComponent(jtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl1)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonOk)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelConstruciton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbConstruction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl0)
                    .addComponent(jButtonOk)
                    .addComponent(jl1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbConstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbConstructionActionPerformed
        // TODO add your handling code here:
        if (this.jcbConstruction.getSelectedIndex() == 0) {
            this.jtf0.setVisible(false);
            this.jtf1.setVisible(false);
            this.jl0.setVisible(false);
            this.jl1.setVisible(false);
            this.jButtonOk.setVisible(false);
            this.jtaCList.setText("");
            this.jtaCList.setVisible(false);
        } else if (this.jcbConstruction.getSelectedIndex() == 1) {
            this.jtf0.setVisible(true);
            this.jtf1.setVisible(true);
            this.jl0.setText("Trappsteg");
            this.jl0.setVisible(true);
            this.jl1.setText("Bredd(mm)");
            this.jl1.setVisible(true);
            this.jButtonOk.setVisible(true);
            this.jtaCList.setText("");
            this.jtaCList.setVisible(false);
        } else if (this.jcbConstruction.getSelectedIndex() == 2) {
            this.jtf0.setVisible(true);
            this.jtf1.setVisible(false);
            this.jl0.setText("Area (m2)");
            this.jl0.setVisible(true);
            this.jl1.setText("");
            this.jl1.setVisible(false);
            this.jButtonOk.setVisible(true);
            this.jtaCList.setText("");
            this.jtaCList.setVisible(false);
        }
    }//GEN-LAST:event_jcbConstructionActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        if (this.jcbConstruction.getSelectedIndex() == 1) {
            Stair s = new Stair(Integer.parseInt(this.jtf0.getText()), Integer.parseInt(this.jtf1.getText()));
            this.jtaCList.append(s.toString());
            this.jtaCList.setVisible(true);
        } else if (this.jcbConstruction.getSelectedIndex() == 2) {
            Foundation s = new Foundation(Integer.parseInt(this.jtf0.getText()));
            this.jtaCList.append(s.toString());
            this.jtaCList.setVisible(true);
        }
    }//GEN-LAST:event_jButtonOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelConstruciton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbConstruction;
    private javax.swing.JLabel jl0;
    private javax.swing.JLabel jl1;
    private javax.swing.JTextArea jtaCList;
    private javax.swing.JTextField jtf0;
    private javax.swing.JTextField jtf1;
    // End of variables declaration//GEN-END:variables
}
